[package]
name = "akh-desktop"
version = "0.1.2"
edition = "2024"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
akh-client = { path = "../../../crates/client" }
akh-core = { path = "../../../crates/core" }
akh-local-server = { path = "../../../crates/local-server" }
serde = { version = "1", features = ["derive"] }
rfd.workspace = true
sqlx.workspace = true
tauri = { version = "2", features = [] }
uuid.workspace = true
