[package]
name = "akh-local-server"
version.workspace = true
edition.workspace = true

[lib]
name = "akh_local_server"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
argon2.workspace = true
axum.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
